### ISSUE TITLE
Update Docs for Delegated Permissions

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/staff-api#182]
Update docs site with relevant information for MS Graph Delegated Permissions

**Comment by w-le** [comment]
Done for Azure AD instructions page.
Todo:
- instructions for adding Tenant in backoffice, with the right scopes (needs backoffice frontend update first to support scopes)
- better instructions for Calendar driver
  - add new scopes settings (with default scope of calendar.readwrite.shared, user.read.all, group.read.all)
  - add role based account (since it would be required with Delegated access)
